// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEOF-0]
	_ = x[TokenNewline-1]
	_ = x[TokenRegister-2]
	_ = x[TokenNumber-3]
	_ = x[TokenIdentifier-4]
	_ = x[TokenInstruction-5]
	_ = x[TokenOpenBracket-6]
	_ = x[TokenClosedBracket-7]
	_ = x[TokenComma-8]
	_ = x[TokenColon-9]
	_ = x[TokenPlus-10]
	_ = x[TOKEN_MINUS-11]
	_ = x[TOKEN_STAR-12]
	_ = x[TOKEN_SLASH-13]
	_ = x[TokenIllegal-14]
}

const _TokenType_name = "TokenEofTokenNewlineTokenRegisterTokenNumberTokenIdentifierTokenInstructionTokenOpenBracketTokenClosedBracketTokenCommaTokenColonTokenPlusTOKEN_MINUSTOKEN_STARTOKEN_SLASHTokenIllegal"

var _TokenType_index = [...]uint8{0, 8, 20, 33, 44, 59, 75, 91, 109, 119, 129, 138, 149, 159, 170, 182}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
