// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEOF-0]
	_ = x[TokenNewline-1]
	_ = x[TokenRegister-2]
	_ = x[TokenNumber-3]
	_ = x[TokenIdentifier-4]
	_ = x[TokenInstruction-5]
	_ = x[TokenOpenBracket-6]
	_ = x[TokenClosedBracket-7]
	_ = x[TokenOpenParenthesis-8]
	_ = x[TokenClosedpParenthesis-9]
	_ = x[TokenComma-10]
	_ = x[TokenColon-11]
	_ = x[TokenPlus-12]
	_ = x[TokenMinus-13]
	_ = x[TokenStar-14]
	_ = x[TokenSlash-15]
	_ = x[TokenIllegal-16]
}

const _TokenType_name = "TokenEOFTokenNewlineTokenRegisterTokenNumberTokenIdentifierTokenInstructionTokenOpenBracketTokenClosedBracketTokenOpenParenthesisTokenClosedpParenthesisTokenCommaTokenColonTokenPlusTokenMinusTokenStarTokenSlashTokenIllegal"

var _TokenType_index = [...]uint8{0, 8, 20, 33, 44, 59, 75, 91, 109, 129, 152, 162, 172, 181, 191, 200, 210, 222}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
