// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpCodeMOV-0]
	_ = x[OpCodeADD-1]
	_ = x[OpCodeSUB-2]
	_ = x[OpCodeMUL-3]
	_ = x[OpCodeDIV-4]
	_ = x[OpCodePUSH-5]
	_ = x[OpCodePOP-6]
	_ = x[OpCodeJMP-7]
	_ = x[OpCodeJE-8]
	_ = x[OpCodeJNE-9]
	_ = x[OpCodeCALL-10]
	_ = x[OpCodeRET-11]
	_ = x[OpCodeCMP-12]
	_ = x[OpCodeHALT-13]
	_ = x[OpCodeUnknown-14]
}

const _OpCode_name = "OpCodeMOVOpCodeADDOpCodeSUBOpCodeMULOpCodeDIVOpCodePUSHOpCodePOPOpCodeJMPOpCodeJEOpCodeJNEOpCodeCALLOpCodeRETOpCodeCMPOpCodeHALTOpCodeUnknown"

var _OpCode_index = [...]uint8{0, 9, 18, 27, 36, 45, 55, 64, 73, 81, 90, 100, 109, 118, 128, 141}

func (i OpCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpCode_index)-1 {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[idx]:_OpCode_index[idx+1]]
}
