// Code generated by "stringer -type=OpCode,RegisterName -output=stringer.go"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpCodeMOV-0]
	_ = x[OpCodeADD-1]
	_ = x[OpCodeSUB-2]
	_ = x[OpCodeMUL-3]
	_ = x[OpCodeDIV-4]
	_ = x[OpCodePUSH-5]
	_ = x[OpCodePOP-6]
	_ = x[OpCodeJMP-7]
	_ = x[OpCodeJE-8]
	_ = x[OpCodeJNE-9]
	_ = x[OpCodeCALL-10]
	_ = x[OpCodeRET-11]
	_ = x[OpCodeCMP-12]
	_ = x[OpCodeHALT-13]
	_ = x[OpCodeUnknown-14]
}

const _OpCode_name = "OpCodeMOVOpCodeADDOpCodeSUBOpCodeMULOpCodeDIVOpCodePUSHOpCodePOPOpCodeJMPOpCodeJEOpCodeJNEOpCodeCALLOpCodeRETOpCodeCMPOpCodeHALTOpCodeUnknown"

var _OpCode_index = [...]uint8{0, 9, 18, 27, 36, 45, 55, 64, 73, 81, 90, 100, 109, 118, 128, 141}

func (i OpCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpCode_index)-1 {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[idx]:_OpCode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RegisterEAX-0]
	_ = x[RegisterECX-1]
	_ = x[RegisterEDX-2]
	_ = x[RegisterEBX-3]
	_ = x[RegisterESI-4]
	_ = x[RegisterEDI-5]
	_ = x[RegisterESP-6]
	_ = x[RegisterEBP-7]
	_ = x[RegisterR8D-8]
	_ = x[RegisterR9D-9]
	_ = x[RegisterR10D-10]
	_ = x[RegisterR11D-11]
	_ = x[RegisterR12D-12]
	_ = x[RegisterR13D-13]
	_ = x[RegisterR14D-14]
	_ = x[RegisterR15D-15]
	_ = x[RegisterUnknown-16]
}

const _RegisterName_name = "RegisterEAXRegisterECXRegisterEDXRegisterEBXRegisterESIRegisterEDIRegisterESPRegisterEBPRegisterR8DRegisterR9DRegisterR10DRegisterR11DRegisterR12DRegisterR13DRegisterR14DRegisterR15DRegisterUnknown"

var _RegisterName_index = [...]uint8{0, 11, 22, 33, 44, 55, 66, 77, 88, 99, 110, 122, 134, 146, 158, 170, 182, 197}

func (i RegisterName) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RegisterName_index)-1 {
		return "RegisterName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RegisterName_name[_RegisterName_index[idx]:_RegisterName_index[idx+1]]
}
